### ISSUE TITLE
Stats page allows user injection via shard.yml keys

### ISSUE THREAD

**Issue by sol-vin** [shardbox/shardbox-web#8]
![oopsie](https://user-images.githubusercontent.com/1298501/104119518-ae95b500-52e4-11eb-8cc4-c391ac006cbf.PNG)

By adding custom keys into shards.yml a project can inject keys into the stats page. 

Issue is live right now:
https://shardbox.org/stats

**Comment by straight-shoota** [comment]
That's actually intended. The purpose of this list is to show which `shard.yml` keys are used "in the wild". Regardless of wether they're formally specified. It also shows obvious typos like `idescription`, `developers_dependencies` or `crsytal` (3 times!). Maybe officially defined keys should be highlighted.
Of course this can be abused to inject text into that page. But the entire site shows external content everywhere. You can place whatever you like into `name` and `description` keys and it shows up on shardbox.org. And readmes are also rendered, even as full HTML.

Unless I'm missing something here, I don't think there is anything more problematic with the keys list.

**Comment by sol-vin** [comment]
> 
> 
> That's actually intended. The purpose of this list is to show which `shard.yml` keys are used "in the wild". Regardless of wether they're formally specified. It also shows obvious typos like `idescription`, `developers_dependencies` or `crsytal` (3 times!). Maybe officially defined keys should be highlighted.
> Of course this can be abused to inject text into that page. But the entire site shows external content everywhere. You can place whatever you like into `name` and `description` keys and it shows up on shardbox.org. And readmes are also rendered, even as full HTML.
> 
> Unless I'm missing something here, I don't think there is anything more problematic with the keys list.

Ah, Wasn't sure if this was intended.
